basePath: /api/v2
definitions:
  handlers.GetHandlerResponse:
    properties:
      isAlive:
        type: boolean
      ver:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:43234
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Server Docs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger CyberpunkAttack Docs
  version: "1.0"
paths:
  /:
    get:
      description: Returns a JSON response indicating the API is alive and the current
        version based on the timestamp.
      produces:
      - application/json
      responses:
        "200":
          description: Response containing isAlive status and version
          schema:
            $ref: '#/definitions/handlers.GetHandlerResponse'
      summary: Check API health and version
      tags:
      - health
swagger: "2.0"
