import type { Metadata } from "next";
import localFont from "next/font/local";
import { Orbitron } from "next/font/google";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const spaceArmor = localFont({
  src: "./fonts/SpaceArmor-vmlv4.woff",
  variable: "--font-space-armor",
  weight: "100 900",
  display: "swap",
});

const boxedRound = Orbitron({
  variable: "--font-orbitron",
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${spaceArmor.variable} ${boxedRound.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
