export enum merchantIds {}

export const boxSizings = {};

export const ADDRESS_MOCK = {
  id: 6815601,
  postcode: "88002",
  region: "Закарпатська",
  district: "Ужгородський",
  city: "Ужгород",
  street: "Ісака Дунаєвського",
  houseNumber: "15",
  apartmentNumber: "0",
  description: null,
  countryside: true,
  posteRestante: false,
  foreignStreetHouseApartment: null,
  detailedInfo:
    "Україна, 88002, Закарпатська, Ужгородський, Ужгород, Ісака Дунаєвського 15, 0",
  created: "2024-10-02T16:51:34",
  lastModified: "2024-10-02T16:51:34",
  country: "UA",
};

const CLIENT_MOCK = {
  uuid: "950a3117-d5ac-42a3-aee4-a0597240eefa",
  name: "Філіппова Каміла",
  firstName: "Каміла",
  middleName: null,
  lastName: "Філіппова",
  latinName: null,
  contactPersonName: null,
  type: "INDIVIDUAL",
  postId: null,
  externalId: null,
  uniqueRegistrationNumber: null,
  counterpartyUuid: "61a10100-d4fb-4d4e-9dda-f9a6f7cd7267",
  counterpartyRegcode: "3765410974",
  addressId: 6815601,
  addresses: [
    {
      uuid: "25f22b46-e2a3-4a34-a01e-18ad59813a12",
      addressId: 6815601,
      address: {
        id: 6815601,
        postcode: "88002",
        region: "Закарпатська",
        district: "Ужгородський",
        city: "Ужгород",
        street: "Ісака Дунаєвського",
        houseNumber: "15",
        apartmentNumber: "0",
        description: null,
        countryside: true,
        posteRestante: false,
        foreignStreetHouseApartment: null,
        detailedInfo:
          "Україна, 88002, Закарпатська, Ужгородський, Ужгород, Ісака Дунаєвського 15, 0",
        created: "2024-10-02T16:51:34",
        lastModified: "2024-10-02T16:51:34",
        country: "UA",
      },
      type: "PHYSICAL",
      main: true,
    },
  ],
  phoneNumber: "+380932369308",
  phones: [
    {
      uuid: "138f5cfe-4d95-430e-bec2-e2c8b0acc6f8",
      phoneId: 6815603,
      phoneNumber: "+380932369308",
      type: "PERSONAL",
      main: true,
      confirmed: false,
    },
  ],
  email: "",
  emails: [],
  bankAccount: null,
  postPayPaymentType: "POSTPAY_PAYMENT_CASH_ONLY",
  accountType: {
    type: "CORPORATE",
    assignmentDate: "2024-10-02",
  },
  crmUuid: null,
  resident: true,
  GDPRRead: false,
  GDPRAccept: false,
  personalDataApproved: false,
  checkOnDeliveryAllowed: true,
  freeStorageAvailable: false,
  returnDaysSettingAvailable: false,
};

const Banderol_MOCK = {
  sender: {
    uuid: "61a10100-d4fb-4d4e-9dda-f9a6f7cd7267",
  },
  recipient: {
    uuid: "950a3117-d5ac-42a3-aee4-a0597240eefa",
  },
  deliveryType: "W2W",
  weight: 1400,
  length: 31,
  width: 38,
  height: 7,
  recommended: false,
  sms: false,
  paidByRecipient: true,
  description: "Cyberpunk Attack",
  parcels: [
    {
      name: "Board Game",
      weight: 1400,
      length: 31,
      declaredPrice: 1200,
    },
  ],
};

const BANDEROL_RESPONSE_MOCK = {
  uuid: "289051d3-3263-4495-87dc-40c316e2cb84",
  type: "EXPRESS",
  sender: {
    uuid: "950a3117-d5ac-42a3-aee4-a0597240eefa",
    name: "Філіппова Каміла",
    firstName: "Каміла",
    middleName: null,
    lastName: "Філіппова",
    latinName: null,
    contactPersonName: null,
    type: "INDIVIDUAL",
    postId: null,
    externalId: null,
    uniqueRegistrationNumber: null,
    counterpartyUuid: "61a10100-d4fb-4d4e-9dda-f9a6f7cd7267",
    counterpartyRegcode: "3765410974",
    addressId: 6815601,
    addresses: [
      {
        uuid: "25f22b46-e2a3-4a34-a01e-18ad59813a12",
        addressId: 6815601,
        address: {
          id: 6815601,
          postcode: "88002",
          region: "Закарпатська",
          district: "Ужгородський",
          city: "Ужгород",
          street: "Ісака Дунаєвського",
          houseNumber: "15",
          apartmentNumber: "0",
          description: null,
          countryside: true,
          posteRestante: false,
          foreignStreetHouseApartment: null,
          detailedInfo:
            "Україна, 88002, Закарпатська, Ужгородський, Ужгород, Ісака Дунаєвського 15, 0",
          created: "2024-10-02T16:51:34",
          lastModified: "2024-10-02T16:51:34",
          country: "UA",
        },
        type: "PHYSICAL",
        main: true,
      },
    ],
    phoneNumber: "+380932369308",
    phones: [
      {
        uuid: "138f5cfe-4d95-430e-bec2-e2c8b0acc6f8",
        phoneId: 6815603,
        phoneNumber: "+380932369308",
        type: "PERSONAL",
        main: true,
        confirmed: false,
      },
    ],
    email: "",
    emails: [],
    bankAccount: null,
    postPayPaymentType: "POSTPAY_PAYMENT_CASH_ONLY",
    accountType: {
      type: "CORPORATE",
      assignmentDate: "2024-10-02",
    },
    crmUuid: null,
    resident: true,
    GDPRRead: false,
    GDPRAccept: false,
    personalDataApproved: false,
    checkOnDeliveryAllowed: true,
    freeStorageAvailable: false,
    returnDaysSettingAvailable: false,
  },
  dropOffPostcode: "88002",
  recipient: {
    uuid: "950a3117-d5ac-42a3-aee4-a0597240eefa",
    name: "Філіппова Каміла",
    firstName: "Каміла",
    middleName: null,
    lastName: "Філіппова",
    latinName: null,
    contactPersonName: null,
    type: "INDIVIDUAL",
    postId: null,
    externalId: null,
    uniqueRegistrationNumber: null,
    counterpartyUuid: "61a10100-d4fb-4d4e-9dda-f9a6f7cd7267",
    counterpartyRegcode: "3765410974",
    addressId: 6815601,
    addresses: [
      {
        uuid: "25f22b46-e2a3-4a34-a01e-18ad59813a12",
        addressId: 6815601,
        address: {
          id: 6815601,
          postcode: "88002",
          region: "Закарпатська",
          district: "Ужгородський",
          city: "Ужгород",
          street: "Ісака Дунаєвського",
          houseNumber: "15",
          apartmentNumber: "0",
          description: null,
          countryside: true,
          posteRestante: false,
          foreignStreetHouseApartment: null,
          detailedInfo:
            "Україна, 88002, Закарпатська, Ужгородський, Ужгород, Ісака Дунаєвського 15, 0",
          created: "2024-10-02T16:51:34",
          lastModified: "2024-10-02T16:51:34",
          country: "UA",
        },
        type: "PHYSICAL",
        main: true,
      },
    ],
    phoneNumber: "+380932369308",
    phones: [
      {
        uuid: "138f5cfe-4d95-430e-bec2-e2c8b0acc6f8",
        phoneId: 6815603,
        phoneNumber: "+380932369308",
        type: "PERSONAL",
        main: true,
        confirmed: false,
      },
    ],
    email: "",
    emails: [],
    bankAccount: null,
    postPayPaymentType: "POSTPAY_PAYMENT_CASH_ONLY",
    accountType: {
      type: "CORPORATE",
      assignmentDate: "2024-10-02",
    },
    crmUuid: null,
    resident: true,
    GDPRRead: false,
    GDPRAccept: false,
    personalDataApproved: false,
    checkOnDeliveryAllowed: true,
    freeStorageAvailable: false,
    returnDaysSettingAvailable: false,
  },
  recipientPhone: "+380932369308",
  recipientEmail: null,
  recipientAddressId: 6815601,
  senderAddressId: 6815601,
  returnAddressId: 6815601,
  shipmentGroupUuid: null,
  externalId: null,
  deliveryType: "W2W",
  packageType: null,
  onFailReceiveType: "RETURN",
  barcode: "0500112280947",
  weight: 1400,
  length: 31,
  width: 0,
  height: 0,
  declaredPrice: 1200,
  deliveryPrice: 26.0,
  rawDeliveryPrice: 26.0,
  returnDeliveryPrice: 15.0,
  postPay: null,
  postPayUah: 0,
  postPayDeliveryPrice: 0,
  currencyCode: null,
  postPayCurrencyCode: null,
  currencyExchangeRate: null,
  lastModified: "2024-10-02T17:06:08",
  created: "2024-10-02T17:06:08",
  description: "Cyberpunk Attack",
  parcels: [
    {
      uuid: "5cb6dd92-450c-4c2e-8101-837214285e34",
      name: "Board Game",
      parcelNumber: 1,
      barcode: "0500112280947",
      contentsType: null,
      weight: 1400,
      length: 31,
      width: null,
      height: null,
      declaredPrice: 1200,
      parcelItems: null,
      description: null,
    },
  ],
  direction: {
    regionSortingCenter: "Ужгород",
    districtSortingCenter: "Депо вірт. Ужгород",
    postOfficeNumber: "88004",
    postOfficeName: "Ужгородський (Ужгород)",
    isAutomated: true,
  },
  lifecycle: {
    status: "CREATED",
    statusDate: "2024-10-02T17:06:08",
  },
  deliveryDate: "2024-10-03T00:00:00",
  calculationDescription:
    "Price=26.00: Calculation contains 1 parcels, new measures are weight:1400, length:31, height:0, width:0; tariff (EXPRESS, POSTOFFICE, 1400 g, 31 cm)=20.00; countryside=0.00; declared price surcharge=6.00; return delivery price=15.00",
  availablePaymentTypes: ["CARD", "CARD_ON_SITE", "CASHLESS", "CASH"],
  returnAfterStorageDays: null,
  isPersonal: false,
  isUniversalType: false,
  placeNumberAsep: "01930",
  paidByRecipient: true,
  postPayPaidByRecipient: true,
  bulky: false,
  fragile: false,
  bees: false,
  freeStorage: false,
  sms: false,
  toReturnToSender: null,
  documentBack: false,
  checkOnDelivery: false,
  transferPostPayToBankAccount: false,
  deliveryPricePaid: false,
  postPayPaid: false,
  postPayDeliveryPricePaid: false,
  packedBySender: false,
  free: false,
  withDeliveryNotification: false,
  fittingAllowed: false,
  personalHanding: false,
  administrativeService: false,
  listOfEnclosedItems: false,
  paidByCardOnline: false,
  transferPostPayToCard: false,
  partialReceiptAllowed: false,
};
